export const INIT_GAME = 'INIT_GAME';
export const START_GAME_ACTION = 'START_GAME_ACTION';
export const UPDATE_GAME_BOARD = 'UPDATE_GAME_BOARD';
export const RESET_GAME_ACTION = 'RESET_GAME_ACTION';
export const RESTART_GAME_ACTION = 'RESTART_GAME_ACTION';
export const SWAP_PLAYER_ACTION = 'SWAP_PLAYER_ACTION';
